### ISSUE TITLE
Post a sale

### ISSUE THREAD

**Issue by aqueeno** [CMPUT291W20/MiniProject1#11]
The user should be prompted for a product id, a sale end date and time, a sale description, a condition, and a reserved price. The fields product id, and reserved price are optional and can be left unanswered. Once the data is entered, proper data should be stored in the database with a unique sale id assigned to the sale and the lister set to the current user. The end date must be in future.

**Comment by d-pacheco** [comment]
Completed for the most part. Need to error check the format of the date and time still
