### ISSUE TITLE
Sale search

### ISSUE THREAD

**Issue by d-pacheco** [CMPUT291W20/MiniProject1#6]
The user should be able to enter one or more keywords and the system should retrieve all active sales that have at least one keyword in either sales description or product description (if the sale is associated with a product). Order the results in a descending order of the number distinct search keywords that appear in either sale description or product description (if the sale is associated with a product)

**Comment by aqueeno** [comment]
It should be a working query, but I'm not sure how to make it so it's a partial match for only one of the keywords. My plan was to turn the search input into a list of keywords but I'm not sure how to compare each of the elements of the list with the description? So right now it's only comparing the description to the search input as a whole string
